<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<<<<<<< HEAD
<testsuite hostname="QA-Scheduler" failures="2" tests="18" name="com.curriculum.Analyze_curriculam" time="119.007" errors="0" timestamp="06 Nov 2018 06:54:05 GMT" skipped="0">
  <testcase classname="com.curriculum.Analyze_curriculam" name="TCED29701" time="19.019"/>
  <testcase classname="com.curriculum.Analyze_curriculam" name="TCED29702" time="4.538"/>
  <testcase classname="com.curriculum.Analyze_curriculam" name="TCED29703" time="0.540">
    <failure message="failed to assert  Health expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: failed to assert  Health expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.curriculum.Analyze_curriculam.TCED29703(Analyze_curriculam.java:135)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TCED29703 -->
  <testcase classname="com.curriculum.Analyze_curriculam" name="TCED29704" time="3.886"/>
  <testcase classname="com.curriculum.Analyze_curriculam" name="TCED29705" time="0.115"/>
  <testcase classname="com.curriculum.Analyze_curriculam" name="TCED29706" time="1.961"/>
  <testcase classname="com.curriculum.Analyze_curriculam" name="TCED29707" time="0.110"/>
  <testcase classname="com.curriculum.Analyze_curriculam" name="TCED29708" time="11.290"/>
  <testcase classname="com.curriculum.Analyze_curriculam" name="TCED29709" time="11.346"/>
  <testcase classname="com.curriculum.Analyze_curriculam" name="TCED29710" time="4.133"/>
  <testcase classname="com.curriculum.Analyze_curriculam" name="TCED29711" time="8.699">
    <failure message="failed to assert  Health expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: failed to assert  Health expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.curriculum.Analyze_curriculam.TCED29711(Analyze_curriculam.java:397)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TCED29711 -->
  <testcase classname="com.curriculum.Analyze_curriculam" name="TCED29712" time="10.044"/>
  <testcase classname="com.curriculum.Analyze_curriculam" name="TCED29713" time="11.272"/>
  <testcase classname="com.curriculum.Analyze_curriculam" name="TCED29714" time="0.865"/>
  <testcase classname="com.curriculum.Analyze_curriculam" name="TCED29715" time="0.188"/>
  <testcase classname="com.curriculum.Analyze_curriculam" name="TCED29716" time="6.002"/>
  <testcase classname="com.curriculum.Analyze_curriculam" name="TCED29717" time="23.635"/>
  <testcase classname="com.curriculum.Analyze_curriculam" name="TCED29718" time="1.364"/>
=======
<testsuite skipped="0" hostname="AKHIL-TS" name="com.curriculum.Analyze_curriculam" tests="18" failures="0" timestamp="6 Nov 2018 08:54:10 GMT" time="136.270" errors="0">
  <testcase name="TCED29712" time="11.324" classname="com.curriculum.Analyze_curriculam"/>
  <testcase name="TCED29707" time="0.260" classname="com.curriculum.Analyze_curriculam"/>
  <testcase name="TCED29705" time="0.167" classname="com.curriculum.Analyze_curriculam"/>
  <testcase name="TCED29717" time="23.506" classname="com.curriculum.Analyze_curriculam"/>
  <testcase name="TCED29715" time="0.341" classname="com.curriculum.Analyze_curriculam"/>
  <testcase name="TCED29714" time="1.126" classname="com.curriculum.Analyze_curriculam"/>
  <testcase name="TCED29703" time="0.828" classname="com.curriculum.Analyze_curriculam"/>
  <testcase name="TCED29704" time="4.227" classname="com.curriculum.Analyze_curriculam"/>
  <testcase name="TCED29706" time="2.913" classname="com.curriculum.Analyze_curriculam"/>
  <testcase name="TCED29709" time="11.330" classname="com.curriculum.Analyze_curriculam"/>
  <testcase name="TCED29710" time="4.306" classname="com.curriculum.Analyze_curriculam"/>
  <testcase name="TCED29716" time="6.333" classname="com.curriculum.Analyze_curriculam"/>
  <testcase name="TCED29718" time="1.325" classname="com.curriculum.Analyze_curriculam"/>
  <testcase name="TCED29713" time="11.284" classname="com.curriculum.Analyze_curriculam"/>
  <testcase name="TCED29701" time="20.294" classname="com.curriculum.Analyze_curriculam"/>
  <testcase name="TCED29708" time="11.310" classname="com.curriculum.Analyze_curriculam"/>
  <testcase name="TCED29711" time="20.961" classname="com.curriculum.Analyze_curriculam"/>
  <testcase name="TCED29702" time="4.435" classname="com.curriculum.Analyze_curriculam"/>
>>>>>>> bdc0d566e812a87ef8ad5c213d22f5917c9e764c
</testsuite> <!-- com.curriculum.Analyze_curriculam -->
