<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="AKHIL-TS" name="com.localassessment.Local_Assessment_Item_Analysisby_Student" tests="5" failures="1" timestamp="17 Oct 2018 10:41:10 GMT" time="18.443" errors="0">
  <testcase name="TCED14122" time="7.177" classname="com.localassessment.Local_Assessment_Item_Analysisby_Student"/>
  <testcase name="TCED14125" time="2.148" classname="com.localassessment.Local_Assessment_Item_Analysisby_Student">
    <failure type="java.lang.AssertionError" message="expected [Percent Correct1] but found [Percent Correct]">
      <![CDATA[java.lang.AssertionError: expected [Percent Correct1] but found [Percent Correct]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.localassessment.Local_Assessment_Item_Analysisby_Student.TCED14125(Local_Assessment_Item_Analysisby_Student.java:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TCED14125 -->
  <testcase name="TCED14123" time="0.314" classname="com.localassessment.Local_Assessment_Item_Analysisby_Student"/>
  <testcase name="TCED14124" time="2.457" classname="com.localassessment.Local_Assessment_Item_Analysisby_Student"/>
  <testcase name="TCED14121" time="6.347" classname="com.localassessment.Local_Assessment_Item_Analysisby_Student"/>
</testsuite> <!-- com.localassessment.Local_Assessment_Item_Analysisby_Student -->
