<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Vofox-Sebastian" name="Report.Mann_Early_Warning" tests="3" failures="1" timestamp="24 Sep 2019 07:02:04 GMT" time="29.849" errors="0">
  <testcase name="TCED37101" time="6.834" classname="Report.Mann_Early_Warning"/>
  <testcase name="TCED37104" time="2.721" classname="Report.Mann_Early_Warning"/>
  <testcase name="TCED37107" time="20.294" classname="Report.Mann_Early_Warning">
    <failure type="java.lang.AssertionError" message="Timeout during waiting for element: &#039;//a[contains(text(),&#039;Mann Early Warning&#039;)]&#039;">
      <![CDATA[java.lang.AssertionError: Timeout during waiting for element: '//a[contains(text(),'Mann Early Warning')]'
at Library.BaseClassOne.waitFor(BaseClassOne.java:276)
at Library.BaseClassOne.click(BaseClassOne.java:188)
at Report.Mann_Early_Warning.TCED37107(Mann_Early_Warning.java:288)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TCED37107 -->
</testsuite> <!-- Report.Mann_Early_Warning -->
