<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="AKHIL-TS" name="com.analyzeByScore.analyzebytagname" tests="15" failures="1" timestamp="8 Nov 2018 11:48:30 GMT" time="200.522" errors="0">
  <testcase name="TCED14321" time="8.721" classname="com.analyzeByScore.analyzebytagname"/>
  <testcase name="TCED14315" time="15.100" classname="com.analyzeByScore.analyzebytagname"/>
  <testcase name="TCED14319" time="8.730" classname="com.analyzeByScore.analyzebytagname"/>
  <testcase name="TCED14309" time="12.120" classname="com.analyzeByScore.analyzebytagname"/>
  <testcase name="TCED14317" time="7.909" classname="com.analyzeByScore.analyzebytagname"/>
  <testcase name="TCED14327" time="54.817" classname="com.analyzeByScore.analyzebytagname"/>
  <testcase name="TCED14316" time="14.114" classname="com.analyzeByScore.analyzebytagname"/>
  <testcase name="TCED14324" time="14.392" classname="com.analyzeByScore.analyzebytagname"/>
  <testcase name="TCED14318" time="0.954" classname="com.analyzeByScore.analyzebytagname">
    <failure type="java.lang.AssertionError" message="expected [Analyze by Tag] but found [Analyze By Tag]">
      <![CDATA[java.lang.AssertionError: expected [Analyze by Tag] but found [Analyze By Tag]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.analyzeByScore.analyzebytagname.TCED14318(analyzebytagname.java:1268)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TCED14318 -->
  <testcase name="TCED14320" time="9.223" classname="com.analyzeByScore.analyzebytagname"/>
  <testcase name="TCED14301" time="6.978" classname="com.analyzeByScore.analyzebytagname"/>
  <testcase name="TCED14323" time="12.287" classname="com.analyzeByScore.analyzebytagname"/>
  <testcase name="TCED14325" time="8.797" classname="com.analyzeByScore.analyzebytagname"/>
  <testcase name="TCED14322" time="8.521" classname="com.analyzeByScore.analyzebytagname"/>
  <testcase name="TCED14326" time="17.859" classname="com.analyzeByScore.analyzebytagname"/>
</testsuite> <!-- com.analyzeByScore.analyzebytagname -->
